"use client";

import { cleanDisplay } from "@/lib/format";
import type { SheetRecord } from "@/lib/types";

export function chatPreview(message?: SheetRecord): string {
  const kind = cleanDisplay(message?.["Media Kind"]).toLowerCase();
  if (kind === "image") return "📷 Foto";
  if (kind === "audio") return "🎤 Nota de voz";
  if (kind === "video") return "🎬 Video";
  if (kind === "document") return "📄 Documento";
  return cleanDisplay(message?.["Message Content Snippet"]);
}

export function MediaBubble({ message }: { message: SheetRecord }) {
  const kind = cleanDisplay(message["Media Kind"]).toLowerCase();
  const src = cleanDisplay(message["Media URL"]);
  const caption = cleanDisplay(message["Message Content Snippet"]);
  const placeholder: Record<string,string> = {
    image: "📷 Imagen recibida",
    audio: "🎤 Nota de voz",
    video: "🎬 Video recibido",
    document: "📄 Documento recibido",
  };
  const visibleCaption = caption !== placeholder[kind] ? caption : "";

  if (kind === "image") {
    return <>
      {src ? <a href={src} target="_blank" rel="noopener noreferrer" title="Open original photo">
        {/* Browser-native original media; not generated by AI. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img className="chatPicture" src={src} alt="Original photo from customer" loading="lazy" />
      </a> : <p>📷 Foto no disponible</p>}
      {visibleCaption && <p className="mediaCaption">{visibleCaption}</p>}
    </>;
  }
  if (kind === "audio") {
    return <>
      <div className="chatAudio">
        <span>🎤 Nota de voz</span>
        {src ? <audio controls preload="none" src={src} aria-label="Reproducir nota de voz">
          Tu navegador no puede reproducir este audio.
        </audio> : <p>Audio no disponible</p>}
      </div>
      {visibleCaption && <p className="mediaCaption">{visibleCaption}</p>}
    </>;
  }
  if (kind === "video") {
    return <>
      {src ? <video controls preload="none" src={src} className="chatVideo" aria-label="Video original" /> : <p>🎬 Video no disponible</p>}
      {visibleCaption && <p className="mediaCaption">{visibleCaption}</p>}
    </>;
  }
  if (kind === "document") {
    return <>
      {src ? <a className="chatDocument" href={src} target="_blank" rel="noopener noreferrer">📄 Ver documento original</a> : <p>📄 Documento no disponible</p>}
      {visibleCaption && <p className="mediaCaption">{visibleCaption}</p>}
    </>;
  }
  return <p>{caption || "[No text]"}</p>;
}
